### ISSUE TITLE
Problems setting up account on “TUTORIAL: How to Create an æternity Account With CLI?” 

### ISSUE THREAD

**Issue by moritzfelipe** [aeternity/tutorials#14] opened 2019-01-09 10:01 UTC
I tried to test your tutorial but got into problems while trying to create an account. Everything works until: “Let’s create our new æternity account: aecli account create my-ae-wallet --password 12345”. 

I get this error message: 
“file:///Users/moritzstellmacher/code/aeternity/cli-test/aepp-cli-js/bin/commands/transaction.js:1
SyntaxError: Missing export name 'commitmentHash' in ES module: file:///Users/moritzstellmacher/code/aeternity/cli-test/aepp-cli-js/node_modules/@aeternity/aepp-sdk/es/tx/js.js
    at Object.Module._extensions..js (module.js:663:10)”

I tried it while running a synced node on mac with mojave and on windows 10. Do you have any idea what could be wrong?

**Comment by VladislavIvanov** [comment] 2019-01-09 14:56
Hi @moritzfelipe ! The ```ae-js-cli``` project is a work-in-progress and your problem looks like a bug. The issue is addressed, I will notify you of further updates. Thank you!

**Comment by mradkov** [comment] 2019-01-11 10:20
I created myself a temporary workaround. I will add the details in a few.

**Comment by thepiwo** [comment] 2019-08-07 07:54
I'll close the issue as the workaround was merged

**Closed by thepiwo** 2019-08-07 07:54 UTC
